### ISSUE TITLE
Possibility to omit ADAM wrapping code. 

### ISSUE THREAD

**Issue by em00k** [boriel/zxbasic#149]
For coding on the ZX Next we have some extra opcodes that control Next Registers. 

Eg

We send bytes $ED92 to activate next register selection. 

Currently ZXB wraps asm with pushes and pops to maintain stability. 

Is it possible to have ASMRAW that would only send the specific bytes sent?

**Comment by boriel** [comment]
AFAIK there is no push/pop around ASM regions. Can you post a little code snippet for clarification? (perhaps it's a bug).

**Comment by em00k** [comment]
As suggested I will use FUNCTION instead of SUB where I want to keep the asm neat!

**Comment by boriel** [comment]
Also, if you want to use plain asm function / subs, you can use `fastcall`:
```
SUB FASCTALL mySub
 ASM
 ...
 END ASM
END SUB
```
