### ISSUE TITLE
Incorrect opcode allowed

### ISSUE THREAD

**Issue by em00k** [boriel/zxbasic#172]
The following code compiles without an error but what happens is e is loaded with lsb of memory address ._c and d lsb of memory address ._c
```
c=10
b=20
ASM 
 ld e,(._c)
 ld d,(._b)
END ASM 
```

While this works correctly 
```
c=10
b=20
ASM 
 ld de,(._c)  ; ._c and ._b are store as a byte next to each other
END ASM 
```

**Comment by boriel** [comment]
Well, that's the expected behavior. :-/ 
c and b variables are truncated to byte. From the ASM point of view `._c` and `._d` are just labels an there's no type information. Perhaps some #pragma or something could be used...

**Comment by jmrodriguez-clv** [comment]
Rereading your comment it seems both `e` and `d` registers loads the content of `.c` variable?

**Comment by boriel** [comment]
Re-reading your issue, do you mean that in the first ASM block both `d` and `e` registers are getting the value of `(._c)`??

**Comment by em00k** [comment]
as mentioned in the chat, this should throw an error : 

![image](https://user-images.githubusercontent.com/22205516/104133327-cb7cc780-537a-11eb-99e3-bfe8aed6f8e2.png)

but it assembles

![image](https://user-images.githubusercontent.com/22205516/104133346-f2d39480-537a-11eb-9bb3-16fb1fea4708.png)

![image](https://user-images.githubusercontent.com/22205516/104133350-fbc46600-537a-11eb-9fcb-9f0fa6bbcb1e.png)

**Comment by boriel** [comment]
Confirmed! It's a bug. Let's fix it! :-)

**Comment by boriel** [comment]
Fixed. Thanks for your report! :-)
