### ISSUE TITLE
Left shift and right shift are flipped

### ISSUE THREAD

**Issue by kjcolley7** [boriel/zxbasic#193]
See referenced code region:

https://github.com/boriel/zxbasic/blob/ad67423f16344dfde638c05afff480d97ee3c016/asmlex.py#L305

It looks like `LSHIFT` is defined to `>>` and `RSHIFT` is defined to `<<`. I just found this while reading through this project's lexer/parser as an example of PLY.

**Comment by boriel** [comment]
Thanks @kjcolley7 
Will fix this ASAP!

**Comment by boriel** [comment]
Update: Despite the names being swapped, the token is evaluated correctly (i.e. `<<` shift to the left). 
https://github.com/boriel/zxbasic/blob/ad67423f16344dfde638c05afff480d97ee3c016/asmparse.py#L207
Anyway, I'll correct it. :)

**Comment by boriel** [comment]
Fixed: https://github.com/boriel/zxbasic/commit/23b28db10e41117805bdb3c0f78543590853b132
