### ISSUE TITLE
Incorrect address given to jr when using contracted lines

### ISSUE THREAD

**Issue by em00k** [boriel/zxbasic#197]
The following code assembles the wrong address for jr z,nextjump

```
asm 

start:
	cp 3 : jr z,nextjump 
	ld hl,data : jr overjump
nextjump:
	ld hl,0
overjump:
	ld a,(hl)
	
data:
	db 2,2		
end asm 

```

![image](https://user-images.githubusercontent.com/22205516/57959601-85006c80-78fc-11e9-9226-5e036adf6cd4.png)

While this works fine : 
```

asm 
start:
	cp 3
	jr z,nextjump 
	ld hl,data
	jr overjump
nextjump:
	ld hl,0
overjump:
	ld a,(hl)	
data:
	db 2,2	
end asm 

``

![image](https://user-images.githubusercontent.com/22205516/57959618-95184c00-78fc-11e9-92c8-671c89a8842c.png)


`

**Comment by em00k** [comment]
![image](https://user-images.githubusercontent.com/22205516/57959630-a3666800-78fc-11e9-8960-f7b53f432902.png)

**Comment by em00k** [comment]
![image](https://user-images.githubusercontent.com/22205516/57959656-c2fd9080-78fc-11e9-93c7-fc9bd10cf3e7.png)

**Comment by boriel** [comment]
Fixed.
For the record this 1.8.11-beta1 release fixes this issue:
http://boriel.com/files/zxb/zxbasic-1.8.11-beta1-win32.zip
http://boriel.com/files/zxb/zxbasic-1.8.11-beta1.tar.gz
http://boriel.com/files/zxb/zxbasic-1.8.11-beta1.zip
