### ISSUE TITLE
Escape chars not being set

### ISSUE THREAD

**Issue by em00k** [boriel/zxbasic#226]
`GetFileSize("c:\\RBC.uue")` should according to the docs send `"c:\RBC.uue"` as a string to the sub GetFileSize but it sends `c:\.BC.uue`

![image](https://user-images.githubusercontent.com/22205516/65835181-17694180-e2db-11e9-81bd-110f8fc0acbd.png)

Should escape chars even be processed when not working with a print string?

**Comment by boriel** [comment]
This might be a bug. Let's trace it...

**Comment by boriel** [comment]
According to the doc, the `\\` should be processed as a backslash:
https://zxbasic.readthedocs.io/en/doc/syntax/

**Comment by boriel** [comment]
Thanks, @em00k !!
