### ISSUE TITLE
BUG: --asm creates assembly code that does not compile (v1.9.4)

### ISSUE THREAD

**Issue by Dotneteer** [boriel/zxbasic#235]
@boriel,

While I was integrating ZX BASIC into SpectNetIDE, this simple code provided an assembly output that does not compile:

```
print "Hello"
```

I attached the .asm file this simple code generates with the `--asm` command line switch.

The `.asm` file references five symbols that do not exist in the file:
- `__SET_ATTR2`
- `INVERSE_TMP`
- `OVER_TMP`
- `BOLD_TMP`
- `ITALIC_TMP`

[Program.asm.txt](https://github.com/boriel/zxbasic/files/3746656/Program.asm.txt)

**Comment by boriel** [comment]
The file asm provided *does* include the labels you mention.

- `__SET_ATTR2` is defined in line 702
- `INVERSE_TMP` is defined in line 571

**Comment by Dotneteer** [comment]
@boriel, thanks a lot :-) I found the cause of the issue: SpectNetIDE assembler takes labels within PROC local (so private), unlike the assembler ZBX uses. I add an option to SpectNetIDE so that I can turn this (default) behavior off.

**Comment by boriel** [comment]
In zxbasm, `PROC` opens a new scope, but labels declared inside must have the `LOCAL` explicit to be considered local.
