### ISSUE TITLE
BUG: "#" characters in an ASM section are not copied to the .asm output (v1.9.4)

### ISSUE THREAD

**Issue by Dotneteer** [boriel/zxbasic#238]
When I have this code, the "#" characters within the asm...end asm section are not copied to the output (using `--asm`):

```
print "Hello"
asm
    ld a,#02
    out (#fe),a
end asm
```

The .asm output contains these code lines:

```
...
#line 1
    ld a,02
    out (fe),a
#line 3
...
```

This results in errors when I compile the code with Z80 assembler (`fe` is not a hexadecimal number, but an identifier)

There might be other characters that are not copied, so far I have found this only one.

**Comment by boriel** [comment]
`#` character is used for preprocessor directives.
Hex numbers are expressed either using the `$` or `0x` prefix, or using the `h` suffix. In the latter case, if the hex number starts with a letter, like `fe`, using `feh` will be ambiguous (it can also be an identifier), so a `0` digit prefix must be used: `0feh`.

This is documented at:
https://zxbasic.readthedocs.io/en/latest/syntax/
