### ISSUE TITLE
BUG: The --asm generates non-compiling output with codes where the HEAP SIZE is zero

### ISSUE THREAD

**Issue by Dotneteer** [boriel/zxbasic#241]
@boriel,

I experienced that ZXB produces an invalid ASM output (`--asm`), provided the code's heap size is zero. Here is a very concise example:

```
PRINT 12345
```

As you can see in the attached file (`Faulty.asm.txt`), at its bottom is generates these labels:

```
ZXBASIC_USER_DATA:
    ; Defines DATA END --> HEAP size is 0
ZXBASIC_USER_DATA_END EQU ZXBASIC_MEM_HEAP
    ; Defines USER DATA Length in bytes
ZXBASIC_USER_DATA_LEN EQU ZXBASIC_USER_DATA_END - ZXBASIC_USER_DATA
```

Unfortunately, the `ZXBASIC_MEM_HEAP` symbol is undefined in the assembly output file.

Should I use a program with non-zero heap size (`Correct.asm.txt`):

```
PRINT 12345
PRINT "HELLO"
```

It generates all the necessary symbols. At the beginning of the code:

```
    org 32768
    ; Defines HEAP SIZE
ZXBASIC_HEAP_SIZE EQU 4096
   ; ...
```

And at the end of the code:

```
ZXBASIC_USER_DATA:
ZXBASIC_MEM_HEAP:
    ; Defines DATA END
ZXBASIC_USER_DATA_END EQU ZXBASIC_MEM_HEAP + ZXBASIC_HEAP_SIZE
    ; Defines USER DATA Length in bytes
ZXBASIC_USER_DATA_LEN EQU ZXBASIC_USER_DATA_END - ZXBASIC_USER_DATA
```

I hope, you can fix this error soon.

Istvan

[Correct.asm.txt](https://github.com/boriel/zxbasic/files/3772972/Correct.asm.txt)
[Faulty.asm.txt](https://github.com/boriel/zxbasic/files/3772973/Faulty.asm.txt)

**Comment by boriel** [comment]
Thanks, @Dotneteer !
Will fix it ASAP.

Explanation: It's indeed a silly bug. It does not affect the assembling because it uses lazy evaluation and since those labels are not referenced afterwards they're being ignored. Hence the Assembler does not complain. :)

**Comment by Dotneteer** [comment]
Thanks :-).

The Z80 Assembler in SpectNetIDE tries to fix-up all labels, independently whether they are used or just declared.

**Comment by Dotneteer** [comment]
@boriel, the newest beta you sent me solves this issue, it seems to fix this bug :-)
