### ISSUE TITLE
Command Documentation

### ISSUE THREAD

**Issue by spectrumcomputing** [boriel/zxbasic#255]
Hi,

Thanks for Boriel, but is there anyway I can help with documentation?

For example, I go to information about the Screen command at:

https://zxbasic.readthedocs.io/en/latest/screen/

At the bottom of the page there are links to:

At the bottom of the page there is:

See also
CSRLIN
POS
AT

None of these seem to work.  I have the same with:

https://zxbasic.readthedocs.io/en/lates ... er/attr.md

If you have any rough notes, I'm happy to type them up for you in Git Flavoured MarkDown.

Best wishes

Peter

**Comment by spectrumcomputing** [comment]
Here is a proposed version of attr.md

##Requirements

ATTR is a library function to be included with the following command:


```
#include <attr.bas>
```

##Sample usage

```
#include <attr.bas>

PRINT AT 9, 10;PAPER 4; "A"
LET s = ATTR$(9, 10)
PRINT AT 0, 0; "The attribute of screen position 9, 10 is "; s
```

##Remarks

* This function extends the one in Sinclair BASIC (and it's compatible with it) since it also allows rows 22 and 23.
* When using _--sinclair_ cmd line parameter this function is already available (i.e. no _#include <screen.bas>_ sentence is needed)

##See also

* [ CSRLIN ](csrlin_.md)
* [ POS](pos_.md)
* [ AT ](at_.md)

**Comment by spectrumcomputing** [comment]
This is something very simple I wrote (I'm a beginner), but may help other beginners with the SCREEN, ATTR and POST commands:

```
#include <screen.bas>
#include <attr.bas>
#include <pos.bas>
CLS
PRINT AT 9, 10;PAPER 4; "A"
LET C$ = SCREEN$(9, 10)
LET A = ATTR$(9, 10)
PRINT AT 0, 0; "The character at 9, 10 is ";C$
PRINT AT 6, 0; "The Attribute at 9, 10 is ";A
PRINT AT 12,0;"0123456789";
Let P = POS()
PRINT AT 18,0; "Current Column Position is ";P
PRINT AT 22,0;"I'm Printing in Row 22 & 23!!"
PRINT AT 23,0; "Press A Key"
PAUSE 0
```

**Comment by boriel** [comment]
Many thanks for this. I'll review them after work :)

**Comment by boriel** [comment]
Please, issue a Pull Request. I'll merge or discuss it in the PR. :-)
