### ISSUE TITLE
ReadTheDocs Hyperlink

### ISSUE THREAD

**Issue by spectrumcomputing** [boriel/zxbasic#261]
Hi again,

Some of the hyperlinks on ReadTheDocs don't seem to be working correctly.

For example, if you go to:

https://zxbasic.readthedocs.io/en/latest/identifier/#inbuilt-library-functions

and click on 'Screen' it takes you here:

https://zxbasic.readthedocs.io/en/latest/screen/

Then if you go to the very bottom of the page under the 'See Also' section and click on 'At', it tries to take you to:

https://zxbasic.readthedocs.io/en/latest/screen/at_.md

when it should be:

https://zxbasic.readthedocs.io/en/latest/at/

I'm OK with Markdown, but I've not used ReadTheDocs before.  If you know what the issue is, I'm very happy to go through all the pages and fix any occurrences of it, buy raising pull requests.

Best wishes

Peter Jones
spectrumcomputing.co.uk

**Comment by boriel** [comment]
The links were wrong (they had an underscore at the end). Fixed.

**Comment by spectrumcomputing** [comment]
Thank you, that's great.
