### ISSUE TITLE
Use the zx emulator to run zxbasic tests

### ISSUE THREAD

**Issue by kosarev** [boriel/zxbasic#283]
@boriel Please see attached. The script merely loads the specified tape file and keeps the machine running until a breakpoint hit, which we expect at PC=0, provided the test source itself is amended as shown in the diff. Please let me know if there's something else needed. Thanks.

[use_zx_to_run_tests.zip.txt](https://github.com/boriel/zxbasic/files/4582978/use_zx_to_run_tests.zip.txt)

**Comment by boriel** [comment]
Definitely!!! OMG thanks very much!! :-) :-) :-)

**Comment by boriel** [comment]
Testing in progress:
https://github.com/boriel/zxbasic/commits/feature/automatize_runtime_tests

**Comment by kosarev** [comment]
@boriel Looks great. Inspired by your new viewer, I have just added the support for .scr files to the emulator. :-)

**Comment by boriel** [comment]
Closed in PR #297
