### ISSUE TITLE
ZXBasic fails to run as a console script

### ISSUE THREAD

**Issue by kosarev** [boriel/zxbasic#313]
The problem seems to be that the `zxb.py` in the root directory effectively imports itself on `import zxb`. Looks like either the script or the same-named package needs to be renamed? Or, you could just remove the script and let the package do its work.

To reproduce:
```shell
$ python3 setup.py develop --prefix ~/.local
$ zxb
Traceback (most recent call last):
  File "/home/kosarev/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'zxb' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kosarev/.local/bin/zxb", line 11, in <module>
    load_entry_point('zxbasic', 'console_scripts', 'zxb')()
  File "/home/kosarev/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kosarev/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/kosarev/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/kosarev/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2453, in resolve
    raise ImportError(str(exc))
ImportError: module 'zxb' has no attribute 'main'
```

**Comment by boriel** [comment]
Yes, setup.py script is outdated!
Will update it, but I'm seriously considering to abandon it.

**Comment by boriel** [comment]
Now you can run it with `zxbc` or `zxb`.
Try it and reopen if it fails :)

**Comment by kosarev** [comment]
The patch doesn't seem to work because the `zxb.py` hiding the `zxb` package is still in place. This prevents the zx emulator to import the `zxb` package when run as a console script, so I have to run it as `python3 -m zx circle.zxb`, which is extra typing comparing to the usual `zx circle.zxb`.

Besides, I was hoping the `entry_points` clause in `setup.py` will survive so people could just do `zxb whatever.bas` and get the image.

**Comment by boriel** [comment]
I wanted to tidy up the directory a bit, so zxb, zxbasm and zxbpp have in their respective folders, whilst leaving the original zxb.py, zxbasm.py and zxbpp.py scripts in the root folder so they can be used as before.

For what you mention, to use zxb from a script, this should work, since it's the way the testing framework tests the compiler.

See:
https://github.com/boriel/zxbasic/blob/master/tests/functional/test.py#L365

How are you invoking the compiler?
Can you post a snippet or guide me to the repo file which is failing?

**Comment by boriel** [comment]
Ah, one more thing:

`zxb` is deprecated (still works) in favour of `zxbc`.
And `zxb` module will be renamed to frontend.

All of this refactors are on the road to ZX Basic 2.x which will include a linker and different target-backends.

**Comment by kosarev** [comment]
> How are you invoking the compiler?

It works when run as a normal Python script and fails when run as a console script via a setup.py's entry point. Please see attached. Here are the steps to reproduce:
```
$ python3 setup.py develop --prefix ~/.local
$ zxb_client
Traceback (most recent call last):
  File "/home/kosarev/.local/bin/zxb_client", line 11, in <module>
    load_entry_point('zxb-client', 'console_scripts', 'zxb_client')()
  File "/home/kosarev/labs/kosarev/github/zx/lab/console/zxb_client.py", line 7, in main
    zxb.main()
AttributeError: module 'zxb' has no attribute 'main'
```

[zxb_client.zip](https://github.com/boriel/zxbasic/files/4671741/zxb_client.zip)

**Comment by boriel** [comment]
Yes, console scripts were removed.
Use just `scripts` entry that are located in `bin/`.

The new `setup.py` uses these:
https://github.com/boriel/zxbasic/blob/master/setup.py#L28

Wiil it work for you with these `scripts`?

**Comment by kosarev** [comment]
I think from the zx emulator I can only import the compiler as a package, that is, by invoking `import zxb`, so it's not really about running it from the command line. Here's how it's currently implemented:
https://github.com/kosarev/zx/commit/c837fbdc36cc8c2096a13e00e832afe41e912fc7#diff-93fabf1b822af63dc933d7d7238b8939R27

Yes, I'd expect one of the `zxb.py` module or the `zxb` package be renamed or the `zxb.py` removed, and the console entry points definitions in `setup.py` brought back. That should resolve the problem, if I'm not missing anything.

**Comment by boriel** [comment]
Ok. I'll have a look.

BTW the provided zxb_client.zip works ok with the current project status (`master` branch).

**Comment by kosarev** [comment]
Hmm. Somehow it fails on my machine with the traceback as shown above. Are you sure you run it as `zxb_client` and not as `zxb_client.py`?

**Comment by boriel** [comment]
Hey!! It's working for me!!!

I created a BASIC program, `hello.zxb`:

`PRINT "HELLO WORLD"

Then pip installed zxbasic directly from the git repo:
`pip install -e $HOME/src/zxbasic`

And this works. However, removing the `-e` flag installs correctly but does not work. Will fix that.

Can you try, please?

**Comment by boriel** [comment]
Also try with this package (`pip install .` in the directory where you uncompress it)
[zxbasic-1.10.0.tar.gz](https://github.com/boriel/zxbasic/files/4672594/zxbasic-1.10.0.tar.gz)

**Comment by kosarev** [comment]
OK, I'm on 74a5d356, and things look like you nailed it. :-) However, for some reason it now can't find its includes. Thanks for looking into it!

```
$ zx circle.zxb
/tmp/tmpn9e6h4tn/circle.zxb:160: Error: file 'addf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:160: Error: file '' not found
/tmp/tmpn9e6h4tn/circle.zxb:161: Error: file 'cos.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:162: Error: file 'divf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:163: Error: file 'ftou32reg.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:164: Error: file 'gtf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:165: Error: file 'ltf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:166: Error: file 'mulf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:167: Error: file 'plot.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:168: Error: file 'pushf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:169: Error: file 'sin.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:170: Error: file 'storef.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:171: Error: file 'subf.asm' not found
/tmp/tmpn9e6h4tn/circle.zxb:172: Error: file 'u32tofreg.asm' not found
zx: ZX Basic compiler returned 1.
```

**Comment by boriel** [comment]
Hmm let me check that. Should work with the commit id you point out.

**Comment by boriel** [comment]
Installing your emulator with `pip -e .` works ok for me.
Can you post the `circle.zxb` listing?

Also, for your project, not that if not installing with `pip -e` but directly with `pip install <directory or github>` I can't invoke `zx` ??

**Comment by kosarev** [comment]
Just re-checked while being on 74a5d3566e8d12fbb375b1d7880823d80bc72e89, and it worked!

The `circle.zxb` is a renamed https://github.com/boriel/zxbasic/blob/726f2490e7512db22ebe2cc0d3bc31e2bfd9be1c/examples/circle.bas .

Looks like all is good now. Closing this. Thanks!
