### ISSUE TITLE
Please could the installation docs be updated

### ISSUE THREAD

**Issue by spectrumcomputing** [boriel/zxbasic#457]
Hi,

In the installation instructions here:

https://zxbasic.readthedocs.io/en/latest/installation/

It says:

Testing your installation
For the .ZIP distribution, type zxb.py (in windows you can type zxb). 

However, if you do that you get 'zxb is deprecated! Use zxbc instead'

Please could the instructions be updated?

Thank you for the great work.

Peter

**Comment by boriel** [comment]
Please check if it's better now, or suggest changes. :)

**Comment by spectrumcomputing** [comment]
Great, thank you!  The documentation has greatly improved over the last couple of years.  Grand job!
