### ISSUE TITLE
Integer maths issue with result of VAL

### ISSUE THREAD

**Issue by patters-syno** [boriel/zxbasic#470]
I'm not sure how to even describe this strange issue. Here is some example code to expose it:
```
DIM temp$ AS STRING = "-20"
DIM intResult AS INTEGER

CLS
PRINT temp$
PRINT VAL(temp$)
PRINT INT(-20)
PRINT INT(VAL(temp$))
intResult=INT(VAL(temp$))
PRINT intResult
```

I would expect this to print -20 for each step (as confirmed in Sinclair BASIC), but far from it - the compiled code displays:
```
-20
-20
-20
-65516
20
```

I presume the 4th result is a variable type issue? (EDIT, confirmed - this matches the 5th result if using a CAST to Integer). But I don't understand how the sign is being lost after the INT function in the 5th example. Examples 1-3 show that in isolation all the component parts of this work fine, but putting them together is breaking my project. I see that the result of a VAL is a float, but converting that to an integer shouldn't affect the sign of the number as far as I understand.

Even `PRINT CAST(FLOAT,INT(VAL(temp$)))` results in 20 not -20

**Comment by boriel** [comment]
This could be a bug in the typecasting. VAL function is that of the Sinclair ROM (for the moment).

**Comment by boriel** [comment]
Try this beta, and tell me. This should fix it :sweat_smile: 
http://www.boriel.com/files/zxb/zxbasic-1.15.0-beta5.tar.gz
http://www.boriel.com/files/zxb/zxbasic-1.15.0-beta5.zip
http://www.boriel.com/files/zxb/zxbasic-1.15.0-beta5-win32.zip
http://www.boriel.com/files/zxb/zxbasic-1.15.0-beta5-linux64.tar.gz
http://www.boriel.com/files/zxb/zxbasic-1.15.0-beta5-macos.tar.gz

**Comment by patters-syno** [comment]
Yes that's fixed. Thanks once again!
