### ISSUE TITLE
nextcreator.py bug

### ISSUE THREAD

**Issue by em00k** [boriel/zxbasic#480]
NEX files are incorrectly being set to 2MB due to this : 

Line 493 of nexcreator.py is 

`    HEADER512.RAM_required = int(HEADER512.num_banks_to_load >= 8)`

should be 

`    HEADER512.RAM_required = int(HEADER512.num_banks_to_load >= 48)`

As per the C source : 

https://github.com/Threetwosevensixseven/NexCreator/blob/9b2ac62d3b7c0f1447bf5d839d88b9a0159fb86f/vs/NexCreator/NexCreator.c#L593

However this is still a bug (even in C source). What is meant to happen is a check to see if bank >=96 is used if so then it requires 2MB, but what the c source is doing is counting how many banks have been filled to see if it is greater than 1MB. A user may not have every bank in 1MB filled but use banks in the 2MB.

Or even a user may generate a 1MB NEX but their program requires 2MB to function so there should be an option.

**Comment by em00k** [comment]
A better solution would be:

`    HEADER512.RAM_required = any(HEADER512.banks[48:])`

Thanks to ped.

**Comment by boriel** [comment]
Fixed! Thanks for reporting! :-)
