### ISSUE TITLE
REQUEST - asm / incbin directive

### ISSUE THREAD

**Issue by programadorhedonista** [boriel/zxbasic#631]
INCBIN as in sjasmplus:

> `INCBIN <filename>[,<offset>[,<length>]]`
> 
> To include a binary file into the outputfile. The offset and length are optional. If negative offset or length is provided, it counts relatively from the end of the file.
> 
> Example:
> 
>    INCBIN "gfx.scc",7         ; include gfx.scc, skip first 7 bytes
>

**Comment by boriel** [comment]
Okay. Here you have an implementation:
http://www.boriel.com/files/zxb/zxbasic-v1.17.0-beta9.tar.gz
http://www.boriel.com/files/zxb/zxbasic-v1.17.0-beta9.zip
http://www.boriel.com/files/zxb/zxbasic-v1.17.0-beta9-win32.zip
http://www.boriel.com/files/zxb/zxbasic-v1.17.0-beta9-linux64.tar.gz
http://www.boriel.com/files/zxb/zxbasic-v1.17.0-beta9-macos.tar.gz

**Comment by boriel** [comment]
This feature will be available from v1.17.0 onwards.
