### ISSUE TITLE
Can't run the app on mac

### ISSUE THREAD

**Issue by CyrilleTanguay** [boriel/zxbasic#666]
Hi,

I'm trying to run zxbasic (I used the official lastest release download and the github version) on mac os ventura 13.4.1 (I used the official lastest release download and the github version) and followed the instructions but when I type "zxbc.py" in the python interpreter (IDLE shell) it returns this:
Github master version:
```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    zxbc.py
NameError: name 'zxbc' is not defined
```
Downloads page version (from the zxbasic website) :
```
Traceback (most recent call last):
  File "<pyshell#14>", line 1, in <module>
    zxbc.py
NameError: name 'zxbc' is not defined
```
The folder is included in my PATH. Am I doing something wrong?

**Comment by boriel** [comment]
From the download page (https://zxbasic.readthedocs.io/en/docs/archive/) download the specific MacOS version, and use `zxbc` launcher instead of `zxbc.py`. This will launch the `zxbc.py`  properly.

**Comment by CyrilleTanguay** [comment]
> From the download page (https://zxbasic.readthedocs.io/en/docs/archive/) download the specific MacOS version, and use `zxbc` launcher instead of `zxbc.py`. This will launch the `zxbc.py` properly.

I'm not sure that I understand... I downloaded the MacOS version and typed 'zxbc' in the interpreter with "/Users/*UserNameOfMyComputer*/Downloads/zxbasic" as the PATH but it didn't worked

**Comment by boriel** [comment]
You said you typed `zxbc.py` first and then `zxbc` in the IDLE interpreter.
The launcher `zxbc`  that comes with your MacOS distribution is just a Bash shell script, that is supposed to be launched from the terminal (shell) command line:

```bash
$ zxbc
```
If the `$PATH`  env var contains the path of the launcher, it should work and show a help screen:

```bash
boriel@boriel-minipc:~$ zxbc
usage: zxbc.py [-h] [-d] [-O OPTIMIZE] [-o OUTPUT_FILE]
               [-T | -t | -A | --parse-only] [-B] [-a] [-S ORG] [-e STDERR]
               [--array-base ARRAY_BASE] [--string-base STRING_BASE] [-Z]
               [-H HEAP_SIZE] [--heap-address HEAP_ADDRESS] [--debug-memory]
               [--debug-array] [--strict-bool] [--enable-break] [-E]
               [--explicit] [-D DEFINES] [-M MEMORY_MAP] [-i | +i]
               [-I INCLUDE_PATH] [--strict] [--headerless] [--version]
               [--append-binary APPEND_BINARY]
               [--append-headless-binary APPEND_HEADLESS_BINARY] [-N]
               [--arch ARCH] [--expect-warnings EXPECT_WARNINGS]
               [-W DISABLE_WARNING] [+W ENABLE_WARNING] [--hide-warning-codes]
               [-F CONFIG_FILE] [--save-config SAVE_CONFIG]
               PROGRAM
zxbc.py: error: the following arguments are required: PROGRAM
```

**Comment by CyrilleTanguay** [comment]
I tried with the normal bash terminal, but it didn't worked either. I typed "cd /Users/UserNameOfMyComputer/Downloads/zxbasic" then typed "zxbc" and had this message: `-bash: zxbc: command not found`

**Comment by boriel** [comment]
For Unix and MacOS shells, use `./zxbc` if you are in the same directory.
But it's better to add that directory to the `$PATH`  so you can execute it normally:

```bash
export PATH=$PATH: /Users/UserNameOfMyComputer/Downloads/zxbasic

zxbc
```

Try this and let me know the results.
Also, for these kind of questions, the {Forum](https://www.boriel.com/forum/) is a good place too. There are plenty of questions there and some of them might be useful to you.

**Comment by CyrilleTanguay** [comment]
It worked now! Thank you very much for your help! I'll check the forum if I have another problem

**Comment by boriel** [comment]
Anytime
