### ISSUE TITLE
License confusion

### ISSUE THREAD

**Issue by Jookia** [boriel/zxbasic#695]
The README says this:

If you modify this project (the compiler .py or anything licensed as GPLv3) in any way you MUST publish the changes you made and submit your contribution to the community under the same license.

Is this an additional restriction on the compiler license? Or is this project under the MIT+GPL licenses?

**Comment by boriel** [comment]
This is the result of the GPLv3. That is, if you modify the compiler to create another project you must publish the sources of such project. There is not additional restriction here.

**Comment by Jookia** [comment]
The GPLv3 does not require you to publish changes and submit it to the community, it only requires you to publish the changes to people you release binaries to. Is publishing changes publicly and submitting them to the community an additional restriction added by this project?

**Comment by boriel** [comment]
Okay. It seems I made a mistake and mentioned "GPLv3"  instead of AGPLv3, so yes, it's a restriction for you, but an extra freedom for other developers.
I will update this paragraph. Thanks for the observation.

**Comment by Jookia** [comment]
The GPLv3 does not allow you to add additional restrictions. You may have to relicense.

**Comment by boriel** [comment]
I'm on it, thanks for your help.

**Comment by boriel** [comment]
Also, to clarify that this only relates to the compiler (.py) software. If you do anything else (i.e. you create a SaaS service that compiles BASIC programs into something) only the files related to the compiler specifically (not to any other 3rd party software).

**Comment by Jookia** [comment]
Could you update the README to explain you don't have to send changes upstream or to people you don't send the compiler to?

**Comment by Jookia** [comment]
I thought I might just circle around and give my full perspective.

First of all, changing to the AGPL without having other contributors agree seems a bit dodgy: As far as I can tell the project was always GPLv3 only, meaning AGPLv3 incompatible. You need to get consent from all the copyright owners in the codebase first. It would have also been good to talk to them about if this is a change that would stop them contributing.

Secondly, the extra requirements to publish the changes and submit them somewhere is incompatible with basically any open source license out there. The first reason is that generally they deal with distributing copies of programs, if there are no copies made or distributed then copyright law doesn't really come in to effect.

The second more broad reason is that it's a bit of an undue and vague burden. In this case, 'publish the changes you made' is vague and doesn't specify how, when, etc. Does publishing them in a book you have to buy count? Submitting the contribution to the community under the same license is also a headache: Do you really want EVERY change a dev has ever made to your project sent your way? Do you want to be constantly closing pull requests?

The third is discrimination: What if the person can't publish or submit the changes for some reason? What if the GitHub project goes down? Is it no longer open source? What if they just don't have Internet access? What if they are a student or worker that don't own the copyright to their own changes? Can they just not modify zxbasic for their own internal use cases? What if they're under an NDA?

The fourth is that the GPL and AGPL legally let people just ignore additional restrictions like this, so the note is incorrect: I don't have to publish the changes or submit them to the community. Nobody does.

You kind of have to choose between getting everyone to agree to relicense the code under some new license that likely isn't open source (or delete their changes and do it anyway?) or make it clear that these are suggestions. I guess the third option is to just keep the notice and trick people?

**Comment by boriel** [comment]
Please, stop trolling:

1. I have already contacted the (few) actual authors of the code, and yes, they agree. And on top of that, let's face it: I have almost solely written the entire codebase (especially the Python code).
2. "Publishing changes made" could be done simply by packaging the compiler code into a zip archive and making it available for download on the same SaaS site you're trying to build. This is not difficult, but there's an even easier way: clone this repository into a new public one and work there. 😉 Yes, if GitHub goes down, the changes will not be available (and neither will this repository nor yours). I'm pretty sure GitHub has the talent and resources to bring it back ASAP. 😆
3. Seriously? If you can set up a SaaS or just publish a site like the one you have, then yes, you definitely can publish the changes there or do as suggested above.
4. I just added AGPL, which basically says exactly that. If you use this software for private purposes as you mentioned above, NO, you don't have to distribute the software. But if you put the software as a SaaS (as an "online service" or as part of such), YES, you have to. And I'm pretty sure you know that.
5. The contribution for the authors is almost entirely, BASIC and Z80 ASM code libs which is already licensed as MIT / Apache license (and yes, this can be used even to make commercial programs, etc). This is something very common in compilers (see the GPL licensing of the GNU C Compiler for example).

The simple fact that you don't want to share the small changes you want to make, and then demand that I do or don't do things to suit your needs, is disappointing.  :disappointed:

**Comment by Jookia** [comment]
If this project is just licensed under the AGPLv3 with no additional restrictions, I'm completely happy with it. I'm happy to share my changes.

But you've added the additional restriction that I must publish every change I've made, even in private, and submit them to you. I can't do that, sorry.
